#!/bin/bash

# configure config files --------------------------------------------------------
sed -i "s/{COLLECTD_SERVER_IP}/$COLLECTD_SERVER_IP/g" /etc/collectd/collectd.conf
sed -i "s/{DB_SERVER_IP}/$DB_SERVER_IP/g" /etc/supervisor/conf.d/PushFaker.conf
sed -i "s/{PROVIDER}/$PROVIDER/g" /etc/supervisor/conf.d/PushFaker.conf

# start the Supervisord
# supervisord -n
service supervisor start

bash
